service: telco-customer-churn-app # Name of the app
runtime: python312 
instance_class: F4

entrypoint: uvicorn app:app --host 0.0.0.0 --port $PORT 

handlers:
- url: /.*
  script: auto  # Automatically route requests to the application
  secure: always  # Force HTTPS

automatic_scaling:
  min_instances: 0 # Minimum number of instances
  max_instances: 1 # Maximum number of instances
  # No more than 5 requests at the same time
  max_concurrent_requests: 5

